# Generated by Django 4.2.19 on 2025-02-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmApp', '0002_alter_category_options_alter_table_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_in_uah',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('UAH', 'Гривня'), ('USD', 'Долар'), ('EUR', 'Євро')], default='UAH', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
