# Generated by Django 4.2.19 on 2025-02-19 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fmApp", "0008_alter_category_name_uk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="name_uk",
        ),
    ]
