# Generated by Django 4.2.18 on 2025-02-20 20:27

from django.db import migrations

def add_default_categories(apps, schema_editor):
    Category = apps.get_model("fmApp", "Category")

    default_categories = [
        ("Groceries", "expense"),
        ("Cafe", "expense"),
        ("Gifts", "expense"),
        ("Mobile Connection", "expense"),
        ("Transport", "expense"),
        ("Transfer", "expense"),
        ("Gym", "expense"),
        ("Entertainment", "expense"),
        ("Subscriptions", "expense"),
        ("Repairs", "expense"),
        ("Pharmacy", "expense"),
        ("Cosmetics", "expense"),
        ("Other", "expense"),
        ("Utility Bills", "expense"),
        ("Hospital", "expense"),
        ("Shopping", "expense"),
        ("Beauty", "expense"),
        ("Planned Purchases", "expense"),
        ("Parking", "expense"),
        ("Transfer", "income"),
        ("Deposit", "income"),
        ("Salary", "income"),
    ]

    for name, category_type in default_categories:
        Category.objects.get_or_create(name=name, type=category_type)


class Migration(migrations.Migration):

    dependencies = [
        ('fmApp', '0009_remove_category_name_uk'),
    ]

    operations = [
        migrations.RunPython(add_default_categories),
    ]
